### ISSUE TITLE
Index out of range runtime error caused panic in forwarder-vpp

### ISSUE THREAD

**Issue by szvincze** [networkservicemesh/cmd-forwarder-vpp#959]
We observed the following runtime error during our tests with NSM v1.11.0. One time it came at upgrade but next time during normal operation without any maintenance activities on the system. See the whole log attached: [forwarder-vpp-2d2xp.log](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/12870206/forwarder-vpp-2d2xp-panic-2.log)

```
Oct 11 13:06:34.182 [TRAC] [id:1fc7c187-6f2b-4acb-80f9-921d721d2b3f] [type:networkService] (55.1)                                                         request-response-diff={"path":{"path_segments":{"4":{"metrics":{"+client_drops":"0","+client_rx_bytes":"0","+client_rx_packets":"0","+client_tx_bytes":"0","+client_tx_packets":"0"}}}}}
time="2023-10-11T13:06:34Z" level=info msg="No subscription found for the notification message." msg_id=714 msg_size=19
Oct 11 13:06:34.182 [DEBU] [id:a331c9ce-8e08-4c68-90a9-39d241df71f7] [DstAddress:172.18.0.11] [SrcAddress:172.18.0.9] [Vni:3448853] [duration:306.803µs] [isAdd:true] [swIfIndex:9] [type:networkService] [vppapi:VxlanAddDelTunnel] (33.2)                                   completed
panic: runtime error: index out of range [9] with length 9

goroutine 11380 [running]:
go.fd.io/govpp/adapter/statsclient.(*statSegmentV2).UpdateEntryData(0x430?, 0x7f62c4c3aa60, 0xc000cfdff8)
	/root/go/pkg/mod/go.fd.io/govpp@v0.8.0/adapter/statsclient/statseg_v2.go:354 +0x77c
go.fd.io/govpp/adapter/statsclient.(*StatsClient).updateStatOnIndex(0xc000200690, 0xc000cfdfc8, 0xc000fde3e8?)
	/root/go/pkg/mod/go.fd.io/govpp@v0.8.0/adapter/statsclient/statsclient.go:633 +0x171
go.fd.io/govpp/adapter/statsclient.(*StatsClient).UpdateDir(0xc000200690, 0xc0008ecba0)
	/root/go/pkg/mod/go.fd.io/govpp@v0.8.0/adapter/statsclient/statsclient.go:294 +0x1e7
go.fd.io/govpp/core.(*StatsConnection).updateStats.func1()
	/root/go/pkg/mod/go.fd.io/govpp@v0.8.0/core/stats.go:220 +0x5b
```

**Comment by denis-tingaikin** [comment]
As I can see, the panic comes from https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/stats/common.go#L46-L47


And it's interesting that we're not doing anything on our side, and it seems like the issue is in the statsclient on the [govpp](https://github.com/networkservicemesh/govpp) side. 


@glazychev-art Do you have any idea?

**Comment by glazychev-art** [comment]
Asked a question to govpp - https://github.com/FDio/govpp/issues/163
